info:
  app:
    name: AgAdminService
    description: EHR platform json app service.
    version: 1.0.0
  component: Zuul Server

eip:
  tenant: jkzl

---
spring:
  profiles: dev
#总部统一网关接口参数配置
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0
zuul:
  routes:
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/

---
spring:
  profiles: prod
#总部统一网关接口参数配置
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0
zuul:
  routes:
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/