logging:
  level:
    com:
      netflix: DEBUG

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 6000

zuul:
  routes:
    adapterDataSet:
      path: /api/v1.0/adapter/plan/adapterDataSet
      serviceId: svr-adaption
    saveDataSetRelationships:
      path: /api/v1.0/std/documents/data_set_relationships
      serviceId: svr-standard
    uploadTemplateFile:
          path: /api/v1.0/templates/{id}/content
          serviceId: svr-health-profile

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

