data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect


---
spring:
  profiles: dev

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

hibernate:
  show-sql: true
  format-sql: true


---
spring:
  profiles: test

data-source:
  url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  username: fujian
  password: fujian

hibernate:
  hibernate-properties:
    hibernate:
      show-sql: true
      format-sql: true

---
spring:
  profiles: prod

data-source:
  url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
  username: ha
  password: jkzlxm

hibernate:
  hibernate-properties:
    hibernate:
      show-sql: false
      format-sql: false

