logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000

zuul:
  routes:
    adapterDataSet:
      path: /api/v1.0/adapter/plan/adapterDataSet
      serviceId: svr-standard
    saveDataSetRelationships:
      path: /api/v1.0/std/documents/data_set_relationships
      serviceId: svr-standard
    uploadTemplateFile:
      path: /api/v1.0/templates/{id}/content
      serviceId: svr-health-profile
    createHosEsbMiniRelease:
      path: /api/v1.0/esb/createHosEsbMiniRelease
      serviceId: svr-esb
    updateHosEsbMiniRelease:
      path: /api/v1.0/esb/updateHosEsbMiniRelease
      serviceId: svr-esb


---
spring:
  profiles: dev
eip:
  schema: hos1
  tenant: ehr

---
spring:
  profiles: alpha
eip:
  schema: hos1
  tenant: ehr

---
spring:
  profiles: test
eip:
  schema: hos1
  tenant: ehr

---
spring:
  profiles: prod
eip:
  schema: hos1
  tenant: ehr

---
spring:
  profiles: prod_fz
eip:
  schema: hos1
  tenant: ehr

---
spring:
  profiles: prod_sr
eip:
  schema: hos1
  tenant: ehr