logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000

zuul:
  routes:
    adapterDataSet:
      path: /api/v1.0/adapter/plan/adapterDataSet
      serviceId: svr-standard
    saveDataSetRelationships:
      path: /api/v1.0/std/documents/data_set_relationships
      serviceId: svr-standard
    uploadTemplateFile:
      path: /api/v1.0/templates/{id}/content
      serviceId: svr-health-profile
    createHosEsbMiniRelease:
      path: /api/v1.0/esb/createHosEsbMiniRelease
      serviceId: svr-esb
    updateHosEsbMiniRelease:
      path: /api/v1.0/esb/updateHosEsbMiniRelease
      serviceId: svr-esb


---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod

---
spring:
  profiles: prod_fz

---
spring:
  profiles: prod_sr
