logging:
  level:
    com:
      netflix: INFO

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 6000

zuul:
  routes:
    adapterDataSet:
      path: /api/v1.0/adapter/plan/adapterDataSet
      serviceId: svr-adaption

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

