zuul:
  routes:
    adapterDataSet:
      path: /api/v1.0/adapter/plan/adapterDataSet
      serviceId: svr-standard
    saveDataSetRelationships:
      path: /api/v1.0/std/documents/data_set_relationships
      serviceId: svr-standard
    uploadTemplateFile:
      path: /api/v1.0/templates/{id}/content
      serviceId: svr-health-profile
    createHosEsbMiniRelease:
      path: /api/v1.0/esb/createHosEsbMiniRelease
      serviceId: svr-esb
    updateHosEsbMiniRelease:
      path: /api/v1.0/esb/updateHosEsbMiniRelease
      serviceId: svr-esb
eip:
  tenant: jkzl

---
spring:
  profiles: dev
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0

---
spring:
  profiles: test

---
spring:
  profiles: prod_fz
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0
---
spring:
  profiles: prod_sr
service-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  handlerId: 50641
  clientId: 9000401
  clientVersion: 1.0

---
spring:
  profiles: prod_fzzy
service-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  handlerId: 50641
  clientId: 9000401
  clientVersion: 1.0