zuul:
  addProxyHeaders: false
  ignoredServices: '*'
  routes:
    packages:
      path: /api/v1.0/packages
      serviceId: svr-pack-mgr
    package_json:
      path: /api/v1.0/json_package
      serviceId: svr-pack-mgr
    esb_log:
      path: /api/v1.0/esb/uploadLog
      serviceId: svr-esb
    sanofi_support:
      path: /api/v1.0/sanofi/physic_signs/**
      serviceId: svr-health-profile
      stripPrefix: false
    health_profile:
      path: /api/v1.0/health_profiles/**
      serviceId: svr-health-profile
      stripPrefix: false
eip:
  tenant: jkzl

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  thymeleaf:
    cache: false
#server:
#  ssl:
#    key-store-password: 123456
#    key-password: 123456

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  thymeleaf:
    cache: false

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ha
    password: jkzlxm
  thymeleaf:
    cache: false

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  thymeleaf:
    cache: false

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  thymeleaf:
    cache: false

---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  thymeleaf:
    cache: false

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  thymeleaf:
    cache: false