zuul:
  ignored-services: "*"
  routes:
    svr-esb: /api/v1.0/esb/uploadLog
    svr-pack-mgr: /api/v1.0/packages

---
spring:
  profiles: dev

  thymeleaf:
    cache: false

server:
  ssl:
    key-store: C:/Windows/tomcat.keystore
    key-store-password: 123456
    key-password: 123456

---
spring:
  profiles: test
  thymeleaf:
    cache: false

server:
  ssl:
    key-store-password: 123456
    key-password: 123456

---
spring:
  profiles: prod

server:
  ssl:
    key-store-password: 123456
    key-password: 123456
