logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000

logging.level.root: INFO

netflix:
  metrics:
    rest:
      metricName: api

# service routes
zuul:
  addProxyHeaders: false
  ignoredServices: '*'
  routes:
    packages:
      path: /api/v1.0/packages
      serviceId: svr-pack-mgr
    package_json:
      path: /api/v1.0/json_package
      serviceId: svr-pack-mgr
    esb_log:
      path: /api/v1.0/esb/uploadLog
      serviceId: svr-esb
    sanofi_support:
      path: /api/v1.0/sanofi/physic_signs/**
      serviceId: svr-health-profile
      stripPrefix: false
    health_profile:
      path: /api/v1.0/health_profiles/**
      serviceId: svr-health-profile
      stripPrefix: false

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha
  thymeleaf:
    cache: false

  metrics:
    export:
      statsd:
        host: 192.168.1.221
        port: 8125

#server:
#  ssl:
#    key-store-password: 123456
#    key-password: 123456

---
spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha

  thymeleaf:
    cache: false

  metrics:
    export:
      statsd:
        host: 192.168.1.221
        port: 8125

server:
  ssl:
    key-store: C:/Windows/tomcat.keystore
    key-store-password: 123456
    key-password: 123456

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: weifuwu
    password: weifuwu
  thymeleaf:
    cache: false

  metrics:
    export:
      statsd:
        host: 172.19.103.73
        port: 8125

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
    username: ha
    password: jkzlxm

server:
  ssl:
    key-store-password: 123456
    key-password: 123456
