logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000

info:
  app:
    name: AgAdminService
    description: EHR platform json app service.
    version: 1.0.0
  component: Zuul Server

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 30000
spring:
  ignoreUrls:
    /api/v1.0/portal/oauth/login;/api/v1.0/portal/oauth/accessToken;/api/v1.0/portal/oauth/refreshToken;/api/v1.0/portal/oauth/validToken;/api/v1.0/portal/portalResourcesTop;/api/v1.0/portal/portalResources

---
spring:
  profiles: dev
eip:
  tenant: jkzl

---
spring:
  profiles: alpha
eip:
  tenant: jkzl

---
spring:
  profiles: test
eip:
  tenant: jkzl

---
spring:
  profiles: prod
eip:
  tenant: jkzl

---
spring:
  profiles: prod_fz
eip:
  tenant: jkzl

---
spring:
  profiles: prod_sr
eip:
  tenant: jkzl
