info:
  app:
    name: AG-ZUUL
    description: EHR Platform Gateway Service
    version: 1.0.0
  component: Zuul Server

spring:
  redis:
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1

---
spring:
  profiles: dev
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: http://ssotest.yihu.cn/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8085/
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/
    # 应急指挥
    emergency-server:
      path: /open/baidu/**
      url: http://yingyan.baidu.com/

---
spring:
  profiles: prod
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: http://ssotest.yihu.cn/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8085/
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn/
    # 应急指挥
    emergency-server:
      path: /open/baidu/**
      url: http://yingyan.baidu.com/