server:
  port: ${ag-zuul.server.port}

info:
  app:
    name: Ag-Zuul
    description:  EHR Platform Zuul Service.
    version: 1.0.0

spring:
  redis:
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1

---
spring:
  profiles: dev
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: http://ssotest.yihu.cn/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8085/
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/

---
spring:
  profiles: test
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: http://ssotest.yihu.cn/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8085/
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/

---
spring:
  profiles: prod_fz
  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    password: Kb6wKDQP1W4
zuul:
  routes:
    jkzl-server:
      path: /jkzl/**
      url: https://api.yihu.com/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8085/
    fastdfs-server:
      path: /file/**
      url: http://11.1.2.9:80/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/

---
spring:
  profiles: prod_sr
  redis:
    host: 10.176.97.5
    port: 6390
    password: q4YaQemf
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: https://api.yihu.com/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8080/
    fastdfs-server:
      path: /file/**
      url: http://10.176.97.5:8888/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/

---
spring:
  profiles: prod_fzzy
  redis:
    host: 100.100.1.161
    port: 6390
    password: q4YaQemf
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: https://api.yihu.com/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8080/
    fastdfs-server:
      path: /file/**
      url: http://100.100.1.157:8888/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/

---
spring:
  profiles: prod_srformal
  redis:
    host: 192.168.50.82
    port: 6379
    password: q4YaQemf
zuul:
  routes:
    # 福州总部开放平台接口相关
    jkzl-server:
      path: /jkzl/**
      url: https://api.yihu.com/OpenPlatform/cgiBin/1.0/
    # 福州总部网关
    fz-gateway:
      path: /fzGateway/**
      url: http://service.yihu.com:8080/
    fastdfs-server:
      path: /file/**
      url: http://192.168.220.62:23000/
    # 卫计委官网
    gov-server:
      path: /open/govServer/**
      url: http://www.srswjw.gov.cn:8080/