server:
  port: ${ag-zuul.server.port}

management:
  port: ${server.port}

info:
  app:
    name: Ag-Zuul
    description:  EHR Platform Zuul Service.
    version: 1.0.0

zuul:
  routes:
    svr-dfs:
      path: /svr-dfs/**
      serviceId: svr-dfs
    svr-ehr-basic:
      path: /svr-ehr-basic/**
      serviceId: svr-ehr-basic
    svr-health-profile:
      path: /svr-health-profile/**
      serviceId: svr-health-profile
    svr-pack-mgr:
      path: /svr-pack-mgr/**
      serviceId: svr-pack-mgr
    svr-pack-resolv:
      path: /svr-pack-resolve/**
      serviceId: svr-pack-resolve
    svr-quota:
      path: /svr-quota/**
      serviceId: svr-quota
    svr-redis:
      path: /svr-redis/**
      serivceId: svr-redis
    svr-resource:
      path: /svr-resource/**
      serviceId: svr-resource
    svr-standard:
      path: /svr-standard/**
      serviceId: svr-standard

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod

---
spring:
  profiles: prod_fz

---
spring:
  profiles: prod_sr