server:
  port: 8011
  session:
    timeout: 30000

spring:
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1  # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  application:
    message: EHR Portal

app:
  clientId: 3CDhsgepr4
  baseClientId: zkGuSIm2Fg  #【基础信息管理】应用

---
spring:
  profiles: dev
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
service-gateway:
  adminInnerUrl: http://172.19.103.73:10000
  zuulOuterUrl: http://27.154.233.186:1235/gateway
  profileInnerUrl: http://172.19.103.73:10000/api/v1.0/admin
server:
  jsp-servlet:
    init-parameters:
      development: true

---
spring:
  profiles: alpha
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
service-gateway:
  adminInnerUrl: http://172.19.103.73:10000
  zuulOuterUrl: http://172.19.103.73:10001
  profileInnerUrl: http://172.19.103.73:10000/api/v1.0/admin

---
spring:
  profiles: prod
  redis:
    host: 192.168.135.40
    port: 6390
    password: redis!@456
service-gateway:
  adminInnerUrl: http://11.1.2.13:10000
  zuulOuterUrl: http://11.1.2.13:10001
  profileInnerUrl: http://11.1.2.13:10000/api/v1.0/admin