server:
  contextPath: /emergency
  port: 9099
  session:
    timeout: 30000000

logging:
  level:
    org.springframework: INFO

spring:
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1  # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  application:
    name: app-emergency-server
    message: EHR Emergency Server

app:
  clientId: 5DloGvRVVZ

---
spring:
  profiles: dev
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
app:
  oauth2InnerUrl: http://172.19.103.73:10260/
  oauth2OuterUrl: http://27.154.233.186:10260/
service-gateway:
  adminInnerUrl: http://172.19.103.73:10000
  profileInnerUrl: http://172.19.103.73:10000/api/v1.0/admin
  yingyanUrl: http://172.19.103.73:10001/open/baidu

---
spring:
  profiles: alpha
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
app:
  oauth2InnerUrl: http://172.19.103.73:10260/
  oauth2OuterUrl: http://27.154.233.186:10260/
service-gateway:
  adminInnerUrl: http://172.19.103.73:10000
  profileInnerUrl: http://172.19.103.73:10000/api/v1.0/admin
  yingyanUrl: http://172.19.103.73:10001/open/baidu

---
spring:
  profiles: prod
  redis:
    host: 192.168.50.82 # Redis server host.
    port: 6379
    password: q4YaQemf
app:
  oauth2InnerUrl: http://192.168.220.84:10000/authentication/
  oauth2OuterUrl: http://jksr.srswjw.gov.cn:1235/gateway/authentication/  #上饶-授权外网映射
service-gateway:
  adminInnerUrl: http://192.168.220.84:10000
  profileInnerUrl: http://192.168.220.84:10000/api/v1.0/admin
  yingyanUrl: http://192.168.220.84:10001/open/baidu
