
#服务端口，以10100开始，每个服务间隔为10，若有新服务，请更新最大端口号。当前最大：10180
svr-adaption.server.port: 10150
svr-app.server.port: 10160
svr-dict.server.port: 10050
svr-esb.server.port: 10130
svr-geography.server.port: 10090
svr-health-profiles.server.port: 9009
svr-organization.server.port: 10070
svr-pack-mgr.server.port: 10140
svr-pack-resolve.server.port: 10170
svr-patient.server.port: 10100
svr-security.server.port: 10110
svr-special-dict.server.port: 10180
svr-standard.server.port: 10040
svr-user.server.port: 10120
ag-ehr-platform.server.port: 443
ag-admin.server.port: 10000

#错误消息
ehr.common.invalid.parameter: 参数解析错误
ehr.common.query.not.found: 不存在该对象
ehr.common.repeat.code: 代码重复

#应用部署所在区域
deploy:
  region: 3502

#用户默认密码
default:
  password: 123456

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  #屏蔽虚拟网卡IP
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - vmnet.*

logging:
  level:
    com:
      netflix: DEBUG

eureka:
  instance:
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://${eureka-server-ip}/eureka/

---
spring:
  profiles: dev

eureka-server-ip: 192.168.1.220:8761

---
spring:
  profiles: test

eureka-server-ip: 172.19.103.73:8761

---
spring:
  profiles: prod

eureka-server-ip: 11.1.2.21:8761
