spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

quartz:
  auto-startup: false

#应用部署所在区域
deploy:
  region: 3502

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
