server:
  port: 8099
  contextPath:
  sessionTimeout:  300

# the name of Camel
camel:
  springboot:
    name: hos-broker

---

spring:
  profiles: dev
  activemq:
    broker-url: tcp://172.19.103.57:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs

log:
  path: /data/logs/hos-broker/dev
  level: info
hos:
  filesystem:
    url: http://172.19.103.58:9010/dfs/file
  arbiter:
    enable: true
    url: http://172.19.103.58:10135
  rest:
    url: http://172.19.103.58:8088
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作
  jcraft:
    host: 172.19.103.57
    port: 22
    user: rootxx
    password: ceshi
hzy:
  hello: hello dev !!!

---

spring:
  profiles: test
  activemq:
      broker-url: tcp://172.19.103.58:61616 # activeMq地址
      user: admin
      password: admin
  data:
    mongodb:
      host: 172.19.103.57 # mongodb 连接信息
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
log:
  path: /data/logs/hos-broker/test  #日志输出地址
  level: info
hos:
  filesystem:
    url: http://172.19.103.58:9010/dfs/file #文件服务器地址
  arbiter:
    enable: true
    url: http://172.19.103.58:10135  # arbiter 的连接地址
  rest:
    url: http://172.19.103.58:8088  # 采集上传档案等服务连接地址
  timer:
      period: 10000
  tenant:
    name: yichang
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作，连接终端服务器的后门信息
  jcraft:
    host: 172.19.103.37
    port: 22
    user: root
    password: ceshi
hzy:
  hello: hello test !!!

---
spring:
  profiles: prod_sr
  activemq:
    broker-url: tcp://192.168.200.60:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
log:
  path: /usr/local/esb/logs/hos-broker
  level: info
hos:
  filesystem:
    url: http://192.168.200.62:9010/dfs/file
  arbiter:
    enable: true
    url: http://192.168.200.62:10135
  rest:
    url: http://192.168.200.62:8088
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作
  jcraft:
    host: 192.168.200.62
    port: 22
    user: root
    password: ceshi
  https:
    enable: false

---
spring:
  profiles: prod_fz
  activemq:
    broker-url: tcp://11.1.2.8:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 11.1.2.3
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
log:
  path: /usr/local/esb/logs/hos-broker
  level: info
hos:
  filesystem:
    url: http://11.1.2.13:9010/dfs/file
  arbiter:
    enable: true
    url: http://11.1.2.13:10135
  rest:
    url: http://11.1.2.13:8088
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作
  jcraft:
    host: 10.176.97.14
    port: 22
    user: root
    password: ceshi
  https:
    enable: false

---
spring:
  profiles: prod_fzzy
  activemq:
    broker-url: tcp://100.100.1.153:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 100.100.1.157
      port: 29000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
eureka:
  client:
    serviceUrl:
      defaultZone: http://100.100.1.162:8761/eureka/
log:
  path: /usr/local/esb/logs/hos-broker
  level: info
hos:
  filesystem:
    url: http://100.100.1.165:9010/dfs/file
  arbiter:
    enable: true
    url: http://100.100.1.165:10135
  rest:
    url: http://100.100.1.165:8088
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作
  jcraft:
    host: 100.100.1.165
    port: 22
    user: root
    password: ceshi
  https:
    enable: false


