security:
  basic:
    enabled: false

---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.103.57:8066/global_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true
    username: hos
    password: 123456
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
# REDIS
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
    database: 0 # Database index used by the connection factory.
    timeout: 0
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 172.19.103.58:9020
  filesystem:
    url: http://172.19.103.58:9010/dfs/file
  adminOutUrl: http://172.19.103.57:7070
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.103.57:8066/global_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true
    username: hos
    password: 123456
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
# REDIS
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
    database: 0 # Database index used by the connection factory.
    timeout: 0 #
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 172.19.103.58:9020
  filesystem:
    url: http://172.19.103.58:9010/dfs/file
  adminOutUrl: http://172.19.103.57:7070
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: prod_sr
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.210.3:3310/tenant_central?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: jkzlesb
    password: Ajch6o@Y
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
# REDIS
  redis:
    host: 192.168.50.82 # Redis server host.
    port: 6379
    password: q4YaQemf
    database: 0 # Database index used by the connection factory.
    timeout: 0 #
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 192.168.200.62:9020
  filesystem:
    url: http://192.168.200.62:9010/dfs/file
  adminOutUrl: http://172.19.103.57:7070  # todo 改成hos-admin微服务外网地址,待确认外网地址  用于采集时,发送消息,将标准相关缓存到mongodb,目前暂时没用
fast-dfs:
  tracker-server: 192.168.50.116:22122,192.168.50.119:22122,192.168.50.116:22123
  public-server: http://192.168.50.37:8888,http://192.168.50.38:8888,http://192.168.50.37:10000
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.176.97.9:3310/tenant_central?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: jkzlesb
    password: Ajch6o@Y
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
# REDIS
  redis:
    host: 10.176.97.5 # Redis server host.
    port: 6390
    password: q4YaQemf
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds. 生产线出现过超时,先配置10000ms
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
  data:
    mongodb:
      host: 10.176.97.9
      port: 29000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 10.176.97.14:9020
  filesystem:
    url: http://10.176.97.14:9010/dfs/file
  adminOutUrl: http://171.35.109.35:81
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: prod_fz
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://11.1.2.5:3310/tenant_jkzl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: jkzlesb
    password: Ajch6o@Y
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
# REDIS
  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    password: Kb6wKDQP1W4
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
  data:
    mongodb:
      host: 11.1.2.3
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 11.1.2.13:9020
  filesystem:
    url: http://11.1.2.13:9010/dfs/file
  adminOutUrl: http://172.19.103.57:7070  # todo 改成hos-admin微服务外网地址,待确认外网地址  用于采集时,发送消息,将标准相关缓存到mongodb,目前暂时没用
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: prod_fzzy
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://100.100.1.159:3310/tenant_jkzl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: jkzlesb
    password: Ajch6o@Y
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    max-total: 100
    default-auto-commit: true
    max-idle: 50
    min-idle: 20
    initial-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    format-sql: true
    show-sql: false
# REDIS
  redis:
    host: 100.100.1.161 # Redis server host.
    port: 6390
    password: q4YaQemf
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  data:
    mongodb:
      host: 100.100.1.157
      port: 29000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      gridFsDatabase: dfs
      database: runtime
  aop:
    proxy-target-class: true
hos:
  saasAdmin: jkzl  #SAAS管理员账号,暂时配置在此处
  clientId: 0e3DIdNaQ2
  zbus:
    url: 100.100.1.165:9020
  filesystem:
    url: http://100.100.1.165:9010/dfs/file
  adminOutUrl: http://172.19.103.57:7070  # todo 改成hos-admin微服务外网地址,待确认外网地址  用于采集时,发送消息,将标准相关缓存到mongodb,目前暂时没用
fast-dfs:
  tracker-server: 100.100.1.157:22122
  public-server: http://100.100.1.157:8888
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "


