server:
  port: 8099
  contextPath:
  sessionTimeout:  300

# the name of Camel
camel:
  springboot:
    name: hos-broker

---

spring:
  profiles: dev
  activemq:
    broker-url: tcp://172.19.103.42:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.19.103.58:8761/eureka/

log:
  path: D://logs/logback/dev
  level: info
hos:
  filesystem:
    url: http://172.19.103.57:9010/dfs/file
  arbiter:
    enable: true
    url: http://192.168.131.106:10135
  rest:
    url: http://172.19.103.57:8088
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作
  jcraft:
    host: 172.19.103.57
    port: 22
    user: rootxx
    password: ceshi
hzy:
  hello: hello dev !!!

---

spring:
  profiles: test
  activemq:
      broker-url: tcp://172.19.103.42:61616 # activeMq地址
      user: admin
      password: admin
  data:
    mongodb:
      host: 172.19.103.57 # mongodb 连接信息
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.19.103.58:8761/eureka/  # eureka发现服务中心地址
log:
  path: /data/logs/hos-broker  #日志输出地址
  level: info
hos:
  filesystem:
    url: http://172.19.103.37:9010/dfs/file #文件服务器地址
  arbiter:
    enable: true
    url: http://172.19.103.57:10135  # arbiter 的连接地址
  rest:
    url: http://172.19.103.57:8088  # 采集上传档案等服务连接地址
  timer:
      period: 10000
  tenant:
    name: jkzl
  mycat:
    path: /usr/local/mycat/   ##mycat的安装目录
  #jcraft shell操作，连接终端服务器的后门信息
  jcraft:
    host: 172.19.103.37
    port: 22
    user: root
    password: ceshi
hzy:
  hello: hello test !!!
