server:
  port: 10135

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 172.19.103.42
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: runtime
  activemq:
    broker-url: tcp://172.19.103.57:61616
    user: admin
    password: admin
arbiter:
  timer:
    period: 10000
  central:
    url: 172.19.103.57:9020
  tenant:
    name: jkzl
  mycat:
    name: mycat172.19.103.42

---
spring:
  profiles: test
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: runtime
  activemq:
    broker-url: tcp://172.19.103.57:61616
    user: admin
    password: admin
arbiter:
  timer:
    period: 10000
  central:
    url: 172.19.103.58:9020
  tenant:
    name: yichang
  mycat:
    name: mycat172.19.103.57

---
spring:
  profiles: prod
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      database: runtime
  activemq:
    broker-url: tcp://192.168.200.60:61616
    user: admin
    password: admin
arbiter:
  timer:
      period: 10000
  central:
    url: 192.168.200.62:9020
  tenant:
    name: jkzl
  mycat:
    name: mycat10.176.97.14
