server:
  port: 0
security:
  basic:
    enabled: false

# the name of Camel
camel:
  springboot:
    name: hos-logger

---
spring:
  profiles: dev
  activemq:
      broker-url: tcp://172.19.103.42:61616
      user: admin
      password: admin
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs

logger:
  tenant: jkzl
  ehr: d:/hos-logger-log

---
spring:
  profiles: test
  activemq:
      broker-url: tcp://172.19.103.57:61616
      user: admin
      password: admin
  data:
    mongodb:
      host: 172.19.103.57
      port: 27017
      username: esb
      password: esb
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs

logger:
  tenant: yichang
  ehr: /usr/local/esb-logs/rolling

---
spring:
  profiles: prod
  activemq:
      broker-url: tcp://192.168.200.60:61616
      user: admin
      password: admin
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlesb
      password: fgu$^ezl
      authenticationDatabase: admin
      database: log
      gridFsDatabase: dfs

logger:
  tenant: jkzl
  ehr: /usr/local/esb-logs/rolling

