#总支撑平台管理参数
admin:
  region: 3502
  default-user-password: 123465

---
spring:
  profiles: test

admin:
  region: 3502

---
spring:
  profiles: dev

admin:
  region: 3500

---
spring:
  profiles: prod

admin:
  region: 3500