hystrix:
  threadpool:
    default:
      coreSize: 60 #并发执行的最大线程数，默认10
      maxQueueSize: 100 #LinkedBlockingQueue的最大队列数，默认-1，使用SynchronousQueue
      #queueSizeRejectionThreshold: 50 #配置该值后，即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝

spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    #password:  # Login password of the redis server.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 11.1.2.22
    port: 6390
    password: Kb6wKDQP1W4
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 10.176.97.5
    port: 6390
    password: q4YaQemf
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 100.100.1.161
    port: 6390
    password: q4YaQemf
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 192.168.50.82
    port: 6379
    password: q4YaQemf
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time