logging:
  level:
    com:
      netflix: DEBUG
      
data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55

multipart:
  max-file-size: 100MB
  max-request-size: 100MB

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30
  charset: ISO8859-1
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    database:
      platform: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: dev

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

fast-dfs:
  tracker-server: 172.19.103.54:22122

---
spring:
  profiles: test

data-source:
  url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: weifuwu
  password: weifuwu

fast-dfs:
  tracker-server: 172.19.103.54:22122
  
---
spring:
  profiles: prod

data-source:
  url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
  user-name: ha
  password: jkzlxm

fast-dfs:
  tracker-server: 11.1.2.9:22122