data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55

redis:
  pool:
    max-total: 10
    max-idle: 5
    min-idle: 3

solr:
  zkClientTimeout: 10000
  zkConnectTimeout: 10000

---
spring:
  profiles: dev

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

redis:
  connection-factory:
    host-name: 172.19.103.47

solr:
  server: http://172.19.103.10:8983/solr
  zookeeper: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr

---
spring:
  profiles: test

data-source:
  url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  username: fujian
  password: fujian

redis:
  connection-factory:
    host-name: 172.17.110.68

solr:
  server: http://172.19.103.10:8983/solr
  zookeeper: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr

---
spring:
  profiles: prod

data-source:
  url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
  username: ha
  password: jkzlxm

redis:
  connection-factory:
    host-name: 11.1.2.20

solr:
  server: http://172.19.103.10:8983/solr
  zookeeper: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr