logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: ${svr-quota.server.port}

management:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.


---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: ha
    password: jkzlxm

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.
---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://192.168.135.39:3310/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: sr_healtharchive
    password: data!@)1

  data:
    solr:
      zk-host: node1.jkzl.com,node2.jkzl.com,node3.jkzl.com:2181/solr # ZooKeeper host address in the form HOST:PORT.

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU

  data:
    solr:
      zk-host: node1.jkzl.com,node2.jkzl.com,node3.jkzl.com:2181/solr # ZooKeeper host address in the form HOST:PORT.