data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha


fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500

  connect-timeout: 2
  network-timeout: 30

  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890



---
spring:
  profiles: dev

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

hibernate:
  show-sql: true
  format-sql: true

fast-dfs:
  tracker-server: 172.19.103.54:22122


---
spring:
  profiles: test

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

hibernate:
  show-sql: true
  format-sql: true

fast-dfs:
  tracker-server: 172.19.103.54:22122


---
spring:
  profiles: prod

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

hibernate:
  show-sql: true
  format-sql: true

fast-dfs:
  tracker-server: 172.19.103.54:22122
