logging:
  level:
    com:
      netflix: DEBUG

spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    port: 6379 # Redis server port.
    password: # Login password of the redis server.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.

  # SOLR (SolrProperties)
  data:
    solr:
      repositories.enabled: true # Enable Solr repositories.

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500

  connect-timeout: 2
  network-timeout: 30
  fast-dfs:
    charset: ISO8859-1

  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

hadoop:
    hbase-properties:
    - dfs.domain.socket.path: /var/lib/hadoop-hdfs/dn_socket
    - hbase.zookeeper.property.maxClientCnxns: 300
    - hbase.zookeeper.useMulti: true
    - hbase.bulkload.staging.dir: /apps/hbase/staging
    - hbase.client.keyvalue.maxsize: 1048576
    - hbase.client.retries.number: 35
    - hbase.client.scanner.caching: 100
    - hbase.cluster.distributed: true
    - hbase.coprocessor.master.classes:
    - hbase.coprocessor.region.classes: org.apache.hadoop.hbase.security.access.SecureBulkLoadEndpoint
    - hbase.coprocessor.regionserver.classes:
    - hbase.defaults.for.version.skip: true
    - hbase.hregion.majorcompaction: 604800000
    - hbase.hregion.majorcompaction.jitter: 0.50
    - hbase.hregion.max.filesize: 10737418240
    - hbase.hregion.memstore.block.multiplier: 4
    - hbase.hregion.memstore.flush.size: 134217728
    - hbase.hregion.memstore.mslab.enabled: true
    - hbase.hstore.blockingStoreFiles: 10
    - hbase.hstore.compaction.max: 10
    - hbase.hstore.compactionThreshold: 3
    - hbase.local.dir: ${hbase.tmp.dir}/local
    - hbase.master.info.bindAddress: 0.0.0.0
    - hbase.master.info.port: 16010
    - hbase.master.port: 16000
    - hbase.regionserver.global.memstore.size: 0.4
    - hbase.regionserver.handler.count: 30
    - hbase.regionserver.info.port: 16030
    - hbase.regionserver.port: 16020
    - hbase.regionserver.wal.codec: org.apache.hadoop.hbase.regionserver.wal.WALCellCodec
    - hbase.replication: true
    - hbase.rootdir: hdfs://nameservice/apps/hbase/data
    - hbase.rpc.controllerfactory.class:
    - hbase.rpc.protection: authentication
    - hbase.rpc.timeout: 90000
    - hbase.security.authentication: simple
    - hbase.security.authorization: false
    - hbase.superuser: hbase
    - hbase.tmp.dir: /tmp/hbase-${user.name}
    - hfile.block.cache.size: 0.40
    - phoenix.functions.allowUserDefinedFunctions:
    - phoenix.query.timeoutMs: 60000
    - replication.replicationsource.implementation: com.ngdata.sep.impl.SepReplicationSource
    - replication.source.nb.capacity: 1000
    - replication.source.ratio: 1.0
    - zookeeper.session.timeout: 90000
    - zookeeper.znode.parent: /hbase-unsecure

profile-persist:
  record-buffer-size: 200   # HBase batch insert record buffer size.

# 提取器参数，从数据集中提取摘要、事件时间与身份标识
extractor:
  # 事件提取参数
  # 门诊从“门诊摘要”与“挂号”数据集提取事件
  # 住院从“病人摘要”，“入院记录”与“病案首页”提取事件
  # 值用于生成事件摘要
  event:
    data-sets:
      - HDSC01_01: 门诊
      - HDSC01_02: 门诊
      - HDSC02_01: 住院
      - HDSC02_02: 住院
      - HDSC02_09: 住院
    meta-data:
      - HDSD00_01_457_D # 挂号时间
      - HDSD00_01_185_D # 出院时间
  # 身份提取参数，从人口学处提取
  identity:
    data-sets:
      - HDSA00_01
    meta-data:
      id-card-no: HDSA00_01_017_S     # 身份标识
      id-card-type: HDSA00_01_016_S   # 身份类型
  # 卡提取参数
  card:
    data-sets:
      - HDSC01_01: 门诊-病人摘要
      - HDSC01_02: 门诊-挂号
      - HDSC02_01: 住院-病人摘要
      - HDSC02_02: 住院-首页
    meta-data:
      - CARD_NO
      - CARD_TYPE

#error code and message

---
spring:
  profiles: dev

  redis:
    host: 192.168.1.220 # Redis server host.

  data:
    solr:
      host: http://172.19.103.10:8983/solr # Solr host. Ignored if "zk-host" is set.
      zk-host: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr # ZooKeeper host address in the form HOST:PORT.

fast-dfs:
  tracker-server: 172.19.103.54:22122

hadoop:
  - hbase.zookeeper.quorum: node2.jkzldev.com,node1.jkzldev.com,node4.jkzldev.com
  - hbase.zookeeper.property.clientPort: 2181

---
spring:
  profiles: test

  redis:
    host: 172.19.103.47 # Redis server host.

  data:
    solr:
      host: http://172.19.103.10:8983/solr # Solr host. Ignored if "zk-host" is set.
      zk-host: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr # ZooKeeper host address in the form HOST:PORT.

fast-dfs:
  tracker-server: 172.19.103.13:22122

hadoop:
  - hbase.zookeeper.quorum: node2.jkzldev.com,node1.jkzldev.com,node4.jkzldev.com
  - hbase.zookeeper.property.clientPort: 2181

---
spring:
  profiles: prod

  redis:
    host: 11.1.2.20 # Redis server host.

  data:
    solr:
      host: http://172.19.103.10:8983/solr # Solr host. Ignored if "zk-host" is set.
      zk-host: host-172-17-110-23,host-172-17-110-27,host-172-17-110-26:2181/solr # ZooKeeper host address in the form HOST:PORT.

fast-dfs:
  tracker-server: 11.1.2.9:22122

hadoop:
  - hbase.zookeeper.quorum: node2.jkzl.com,node3.jkzl.com,node1.jkzl.com
  - hbase.zookeeper.property.clientPort: 2181