logging:
  level:
    root: INFO
#kafka:
 # broker:
  #  address: node1.hde.h3c.com:6667
#zookeeper:
 # broker:
  #  address: node1.hde.h3c.com:2181,node2.hde.h3c.com:2181
spring:
  session:
    store-type: none
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
service-gateway:
  username: user
  password: eureka
  url: http://192.168.1.221:10000/api/v1.0/admin
kafka:
  broker:
    address: node1.hde.h3c.com:6667
zookeeper:
  broker:
    address: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com:2181

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
service-gateway:
  username: user
  password: eureka
  url: http://192.168.220.84:10000/api/v1.0/admin
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlehr
      password: GMLBq1LG
      authenticationDatabase: admin
      database: ehr
kafka:
  broker:
    address: 172.10.10.2:6667,172.10.10.5:6667
es:
  index: wlyy_quota
  type: wlyy_quota
  host:  http://172.10.10.5:9200
  tHost: 172.10.10.5:9300
  clusterName: jkzl
zookeeper:
  broker:
    address: node1.jkzl.com,node2.jkzl.com,node4.jkzl.com:2181
