standard-svr:
  schema-storage-path: "d:/"

data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect


---
spring:
  profiles: dev

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30
  fast-dfs:
    charset: ISO8859-1
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890
---
spring:
  profiles: test

---
spring:
  profiles: prod
