logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR


spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    #host: 172.19.103.47 # Redis server host.
    port: 6379 # Redis server port.
    password: # Login password of the redis server.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.

    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.

  # SOLR (SolrProperties)

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500

  connect-timeout: 2
  network-timeout: 30
  charset: ISO8859-1

  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

# 就诊事件与CDA文档类型关联
cda-document-type-options:
  event-type:
    - "0": 0dae00065684c9920dc35654490aa9ac   # 门诊
    - "1": 0dae00065684cb220dc35654490aa9ae   # 住院

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  application:
    id: JKZL

fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
eip:
  tenant: jkzl

---
spring:
  profiles: alpha

  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ha
    password: ha
  application:
    id: JKZL


fast-dfs:
  tracker-server: 172.19.103.54:22122
  public-server: http://172.19.103.54:80
eip:
  tenant: jkzl

---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  application:
    id: JKZL

fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
eip:
  tenant: jkzl

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ha
    password: jkzlxm
  application:
    id: JKZL


fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://ds.ehr.yihu.com:22122
eip:
  tenant: jkzl


---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    password: Kb6wKDQP1W4
  application:
    id: JKZL
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80
eip:
  tenant: jkzl

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 10.176.97.5 # Redis server host.
    port: 6390
    password: q4YaQemf

  application:
    id: JKZL
fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:8888
eip:
  tenant: jkzl

---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 100.100.1.161 # Redis server host.
    port: 6390
    password: q4YaQemf

  application:
    id: JKZL
fast-dfs:
  tracker-server: 100.100.1.157:22122
  public-server: http://100.100.1.157:8888
eip:
  tenant: jkzl
