management:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
fast-dfs:
  connect-timeout: 10
  network-timeout: 60
  charset: ISO8859-1
  pool:
    init-size: 1
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890
eip:
  tenant: jkzl
  #健康上饶app-卫计委机构编码--用于居民注册设置默认权限
jksr-app:
  orgcode: PDY026797

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  data:
    mongodb:
      host: 192.168.1.220
      port: 27017
      username: admin
      password: admin
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.19.103.68:9200
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl
h5:
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  data:
    mongodb:
      host: 192.168.1.220
      port: 27017
      username: admin
      password: admin
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.19.103.68:9200
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl
h5:
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    # Login password of the redis server.
    password: Kb6wKDQP1W4
  data:
    mongodb:
      host: 11.1.2.19
      port: 20000
      username: jkzlehr
      password: GMLBq1LG
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.19.103.68:9200
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl
h5:
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 10.176.97.5 # Redis server host.
    port: 6390
    password: q4YaQemf
  data:
    mongodb:
      host: 10.176.97.9
      port: 29000
      username: jkzlehr
      password: GMLBq1LG
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://10.176.97.7:9200
fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:8888
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://10.176.97.7:9200
  tHost: 10.176.97.7:9300
  clusterName: jkzl
h5:
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2

---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 100.100.1.161 # Redis server host.
    port: 6390
    password: q4YaQemf
  data:
    mongodb:
      host: 100.100.1.157
      port: 29000
      username: jkzlehr
      password: GMLBq1LG
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://100.100.1.158:9200
fast-dfs:
  tracker-server: 100.100.1.157:22122
  public-server: http://100.100.1.157:8888
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://100.100.1.158:9200
  tHost: 100.100.1.158:9300
  clusterName: jkzl
h5:
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  # -- unknown use --
  ldap:
    host: 192.168.210.3
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 192.168.50.82 # Redis server host.
    port: 6379
    password: q4YaQemf
  data:
    mongodb:
      host: 192.168.50.26
      port: 20000
      username: jkzlehr
      password: GMLBq1LG
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.10.10.2:9200
fast-dfs:
  tracker-server: 192.168.50.116:22122,192.168.50.119:22122
  public-server: http://192.168.50.37:8888
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.10.10.2:9200
  tHost: 172.10.10.2:9300
  clusterName: jkzl
h5:
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: 9U6PBF2JM3PE1IHRJ7GEITMJHNMEHOFZQ2XUCKD9TO2
