spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
  application:
    id: JKZL

fast-dfs:
  connect-timeout: 10
  network-timeout: 60
  charset: ISO8859-1
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

# 就诊事件与CDA文档类型关联
cda-document-type-options:
  event-type:
    - "0": 0dae00065684c9920dc35654490aa9ac   # 门诊
    - "1": 0dae00065684cb220dc35654490aa9ae   # 住院

eip:
  tenant: jkzl

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 11.1.2.22
    port: 6390
    password: Kb6wKDQP1W4
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 10.176.97.5
    port: 6390
    password: q4YaQemf
fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:8888

---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 100.100.1.161
    port: 6390
    password: q4YaQemf
fast-dfs:
  tracker-server: 100.100.1.157:22122
  public-server: http://100.100.1.157:8888

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 192.168.50.82
    port: 6379
    password: q4YaQemf
fast-dfs:
  tracker-server: 192.168.50.116:22122,192.168.50.119:22122,192.168.50.116:22123
  public-server: http://192.168.50.37:8888,http://192.168.50.38:8888,http://192.168.50.37:10000