info:
  app:
    name: SVR-DFS
    description: EHR Platform Microservice.
    version: 1.0.0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
    max-idle: 2
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: true

fast-dfs:
  connect-timeout: 10
  network-timeout: 60
  charset: ISO8859-1
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890
  server:
    dict-code: FASTDFSWLDZ #外链地址系统字典拼音编码
  index:
    name: dfs #ES索引名称
    type: info #ES索引类型

elasticsearch:
  pool:
    init-size: 2
    max-size: 5

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan1
    password: chenweishan
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80