logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR
      
hadoop:
  hbase-properties:
    - hbase.zookeeper.property.clientPort: 2181
    - zookeeper.znode.parent: /hbase-unsecure

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha

  redis:
    host: 192.168.1.220 # Redis server host.

  data:
    solr:
      zk-host: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com:2181/solr # ZooKeeper host address in the form HOST:PORT.
      #zk-host: node1,node2,node3:2181/solr # ZooKeeper host address in the form HOST:PORT.

hadoop:
  hbase-properties:
    - hbase.zookeeper.quorum: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com
    #- hbase.zookeeper.quorum: node1,node2,node3

---
spring:
  profiles: alpha

  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha

  redis:
    host: 192.168.1.220 # Redis server host.

  data:
    solr:
      zk-host: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com:2181/solr # ZooKeeper host address in the form HOST:PORT.
      #zk-host: node1,node2,node3:2181/solr # ZooKeeper host address in the form HOST:PORT.


hadoop:
  hbase-properties:
    - hbase.zookeeper.quorum: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com
    #- hbase.zookeeper.quorum: node1,node2,node3

---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: weifuwu
    password: weifuwu

  redis:
    host: 172.19.103.47 # Redis server host.

  data:
    solr:
      zk-host: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com:2181/solr # ZooKeeper host address in the form HOST:PORT.
      #zk-host: node1,node2,node3:2181/solr # ZooKeeper host address in the form HOST:PORT.


hadoop:
  hbase-properties:
    - hbase.zookeeper.quorum: node1.jkzldev.com,node2.jkzldev.com,node4.jkzldev.com
    #- hbase.zookeeper.quorum: node1,node2,node3

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
    username: ha
    password: jkzlxm

  redis:
    host: 11.1.2.20 # Redis server host.

  data:
    solr:
      zk-host: 11.1.2.51,11.1.2.52,11.1.2.53:2181/solr # ZooKeeper host address in the form HOST:PORT.

hadoop:
  hbase-properties:
    - hbase.zookeeper.quorum: node2.jkzl.com,node3.jkzl.com,node1.jkzl.com
