spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha

---
spring:
  profiles: test

  datasource:
      url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
      username: weifuwu
      password: weifuwu


---
spring:
  profiles: prod

  datasource:
      url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
      username: ha
      password: jkzlxm